apiVersion: integration/v1
kind: Integration
name: kubernetes
channel: stable
version: v20200408
summary: Kubernetes
description: |
    Kubernetes is an open-source system for automating deployment, scaling, and management of containerized applications.
license: Apache-2.0
owner:
  name: Puppet, Inc.
  email: relay@puppet.com
  url: https://puppet.com
homepage: https://github.com/relay-integrations/relay-kubernetes
source: git://github.com/relay-integrations/relay-kubernetes.git
tags:
  - kubernetes
