apiVersion: integration/v1
kind: Step
name: kubectl
version: 3
summary: Run kubectl command

description: |
  Provides general `kubectl` use and can take `kubectl` commands.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/kubernetes-step-kubectl

schemas:
  spec:
    source: file
    file: spec.schema.json

examples:
- summary: Execute kubectl apply
  content:
    apiVersion: v1
    kind: Step
    name: kubectl-command
    image: relaysh/kubernetes-step-kubectl
    spec:
      command: apply
      file: ${parameters.file} # Example: infra/resources.yaml
      namespace: ${parameters.namespace} # Example: default
      cluster:
        name: my-cluster
        connection: ${connections.kubernetes.my-cluster}
      git:
        name: ${parameters.my-repo} # Example: my-git-repo
        branch: ${parametes.branch} # Example: main
        repository: ${parameters.repository} # Example: https://github.com/relay-integrations/relay-kubernetes
- summary: Execute kubectl get nodes
  content:
    apiVersion: v1
    kind: Step
    name: kubectl-command
    image: relaysh/kubernetes-step-kubectl
    spec:
      command: get pods
      namespace: ${parameters.namespace} # Example: default
      cluster:
        name: my-cluster
        connection: ${connections.kubernetes.my-cluster}
