apiVersion: integration/v1
kind: Step
name: kubernetes-step-kubectl
version: 3
summary: Kubectl
description: This Kubectl step container allows general `kubectl` use and can take `kubectl` commands.
icon:
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/kubernetes-step-kubectl
schemas:
  spec: 
    source: file
    file: spec.schema.json
examples:
- summary: Execute kubectl command
  content:
    apiVersion: v1
    kind: Step
    name: kubectl-command
    image: relaysh/kubernetes-step-kubectl
    spec: 
      command: apply
      args: 
      - "-k"
      - "dir/"
      file: infra/resources.yaml
      namespace: default
      cluster:
        name: my-cluster
        connection: !Connection { type: kubernetes, name: my-cluster }
      git: 
        ssh_key:
          $type: Secret
          name: ssh_key
        known_hosts:
          $type: Secret
          name: known_hosts
        name: my-git-repo
        branch: dev
        repository: path/to/your/repo