apiVersion: integration/v1
kind: Step
name: kubernetes-step-kubectl
version: 3
summary: Kubectl
description: This Kubectl step container allows general `kubectl` use and can take `kubectl` commands.
icon:
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/kubernetes-step-kubectl
schemas:
  spec: 
    source: file
    file: spec.schema.json